<a href="https://colab.research.google.com/github/dongmin-jeong/Pandas/blob/main/Kaggle_Pandas_26_07_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kaggle, Pandas** 26-07-02

**Lesson 5. Data Types and Missing Values**

In this section, we will learn how to investigate data types within a DataFrame or Series. We will also learn how to find and replace entries.


The data type for a column in a DataFrame or a Series is known as the dtype. We can use the dtype property to grab the type of a specific column.

In [1]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [2]:
titanic=pd.read_csv('titanic.csv')
titanic.head()
#언제나처럼, 데이터 불러온 뒤 데이터가 잘 로딩됐는지 확인한다.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
titanic.Embarked.dtype
#특정 칼럼의 data type을 확인한다.

dtype('O')

In [5]:
titanic.dtypes
#전체 모든 칼럼의 data type을 확인한다.

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Data types tell us something about how pandas is storing the data internally. Note, the columns consist entirely of strings do not get their own type; they are instead given the object type.

It is possible to convert a column of one type into another wherever such a coversion makes sense by using the astype() function.

In [6]:
titanic.Parch.astype('float64')
#.astype()을 이용하여 Parch 칼럼의 data type을 int64에서 float64로 바꿈

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
886    0.0
887    0.0
888    2.0
889    0.0
890    0.0
Name: Parch, Length: 891, dtype: float64

Entries missing values are given the value NaN, short for Not a Number. For technical reasons, these NaN values are always of the float64 dtype.

Pandas provides some methods specific to missing data. To select NaN entries, we can use pd.isnull().

In [8]:
titanic[pd.isnull(titanic.Age)]
#pd.isnull()의 용법 ; df[pd.isnull(df.칼럼)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [13]:
titanic.Age.isnull()
#곧바로 .isnull() 메서드를 적용하면 Boolean series를 얻는다.
#Boolean series는 NaN에 대해 True를 반환하는 것으로, .sum()을 마지막에 붙이면 NaN의 개수를 알 수 있다.

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [14]:
titanic[titanic.Age.isnull()]
#이렇게 해도 Age가 NaN인 행들로 만들어진 DataFrame을 얻는다.
#titanic[pd.isnull(titanic.Age)]와 완전히 같다?

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

Replacing missing values is a common operation. Pandas provides a really handy method for this problem ; fillna() provides a few different strategies for mitigating such data.

In [9]:
titanic.Age.fillna("?")
#.fillna()의 괄호 안에 NaN을 대체하고 싶은 string / integer를 넣을 수 있다.

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888       ?
889    26.0
890    32.0
Name: Age, Length: 891, dtype: object

In [11]:
titanic.Age.fillna(titanic.Age.mean())
#fillna()를 이용하여 NaN 값에 titanic.Age.mean() 즉 나이평균값을 넣었다.

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

Alternatively, we may have a non-null value that we would like to replace. One way to reflect this in the dataset is using the replace() method.

In [12]:
titanic.Embarked.replace("C", "A")
#titanic.Embarked의 "C"를 "A"로 바꾸기 위하여 replace() 메서드를 이용할 수 있다.

0      S
1      A
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    A
890    Q
Name: Embarked, Length: 891, dtype: object

**Exeercise**

4. What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the region_1 field. This field is often missing data, so replace missing values with Unknown. Sort in descending order.

In [ ]:
#a=reviews.region_1.fillna("Unknown")
#reviews_per_region = a.value_counts(ascending=False)

**Lesson 6. Renaming and Combining**

Oftentimes, data will come to us with column names, index names, or other naming conventions that we are not satisfied with. In that case, we will learn how to use pandas functions to change the names of the offending entreis to something better.

The first function is rename(), which let us change index names and/or column names.

In [15]:
titanic.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [16]:
titanic.rename(columns={'Pclass':'Class'})
#column의 이름을 바꾸고 싶을 때 columns={"원래 이름":"바꾸고 싶은 이름"} 형식으로 지정
#여러 형식이 있지만, python dictionary 형식이 제일 편리하다.

,PassengerId,Survived,Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
#가로의 index 항목을 바꾸고 싶을 때는,
titanic.rename(index={0:'First', 1:'Second', 2:'Third'})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
First,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
Second,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
Third,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Both the row index and the column index can have their own name attribute. The complimentary rename_axis() method may be used to change these names.

그러니까, 행 / 열 그 자체의 이름을 붙이거나 바꿔주는 것이다.

In [18]:
titanic.rename_axis("person", axis='rows').rename_axis("details", axis='columns')
#그런데 이게 왜 중요한건지는 아직 잘 모르겠다.

details,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
person,,,,,,,,,,,,
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

When performing operations on a dataset, we will sometimes need to combine different DataFrames and/or Series in non-trivial ways. Pandas has three core methods for doing this. In order of increasing complexity, these are concat(), join() and merge().

But most of what merge() can do can also be done more simply with join().

The simplest combining method is concat(). Given a list of elements, this function will smush those elements together along an axis.

이 부분은 나중에 필요할 때 따로 공부하기?