<a href="https://colab.research.google.com/github/dongmin-jeong/Pandas/blob/main/Kaggle_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kaggle / Pandas**
2026-06-26

**Lesson 1. Creating, Reading and Writing**

In [ ]:
import pandas as pd
print("Setup complete.")

Setup complete.

Exercise 1. In the cell below, create a DataFrame "fruits" that looks like this;

\begin{bmatrix} \text{Apples} & \text{Bananas} \\ 30 & 21\end{bmatrix}

To solve the problem, we begin our study on the tutorials.

There are two core objects in pandas: the **DataFrame** and the **Series**. A DataFrame is a table.

In [ ]:
pd.DataFrame({'Yes':[50, 21], 'No':[131, 2]})

   Yes   No
0   50  131
1   21    2

"0, No" entry has the value of 131. "0, Yes" entry has the value of 50.

DataFrame entries are not limited to integers.

In [ ]:
pd.DataFrame({'Bob':['I liked it.', 'It was awful.'], 'Sue':['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

We are using the pd.DataFrame() constructor to generate these DataFrame objects. The syntax is basically a dictionary, whose keys are the column names and values are a list of entries.

To assign the row labels, we use an index parameter in our constructor.

In [ ]:
pd.DataFrame({'Bob':['I liked it.', 'It was awful'], 'Sue':['Pretty good.', 'Bland.']}, index=['Product A', 'Product B'])

                    Bob           Sue
Product A   I liked it.  Pretty good.
Product B  It was awful        Bland.

A Series, by contrast, is a sequence of data values.A DataFrame is a table, while a Series is a list. We create nothing more than a list.

In [ ]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series(['a', 'b', 'c'])

0    a
1    b
2    c
dtype: object

A Series is, in essence, a single column of a DataFrame. So we can assign row labels to the Series by the same way as before, using an index parameter. Howefer, a Series does not have a column label.

In [ ]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

The Series and DataFrame are intimately related. It's helpful to think of a DataFrame as actually being just a bunch of Series, glued together.

**Reading data files**

In most cases, the data files are stored in the format of CSV file. When you open a CSV file, you get something that lloks like

Product A, Product B, Product C,

30, 21, 9,

35, 33, 1,

4, 23, 5,

So a CSV file is a table of values separated by commas. CSV stnads for Comma-Separated-Values. We use pd.read_csv() function to read the data into a DataFrame.

.shpe() method checks the scale of the DataFrame.

.head() method shows first five rows of the DataFrame.

.to_csv("파일명")을 이용하여 DataFrame을 csv 파일로 디스크에 저장할 수 있다.

In [ ]:
#read the csv file named ../input/wine-reviews/winemag-data_first150k.csv
pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv", index_col=0)

In [ ]:
animals=pd.DataFrame({"Cows":[12, 20], "Goats":[22, 19]}, index=["Year 1", "Year 2"])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [ ]:
#save this DataFrame to disk as a csv file with the name cows_and_goats.csv
animals.to_csv("cows_and_goats.csv")

**Lesson 2. Indexing, Selecting and Assigning**

이번 단원까지 끝낸 뒤 실제 데이터를 통해 실습해보자.

Native Python objects provide good ways of indexing data. Pandas carries all of these over, which helps make it easy to start with:

reviews=pd.read_csv("~~")

reviews.country

reviews.points

review.province

등 .~~~를 이용하여 reviews라는 DataFrame의 column을 따로 떼어 볼 수 있다. 혹은, DataFrame을 dictionary로 생각하여 value 값들을 모두 불러오는 것도 같은 효과를 준다.

reviews['country']

reviews['province']

이 방법을 이용하여 DataFrame에서 특정 Series를 떼어올 수 있다. 웬만하면 두 번째 방법이 더 좋다.

reviews['country'][0]

과 같이 특정 value만 떼어오는 것도 가능하다.

**Indexing in pandas**

Python의 여러 indexing operator를 pandas에서 그대로 사용할 수 있다. 여기에 loc / iloc operator가 추가된다.

Pandas indexing works in one of two paradigms. The firsts is index-based selection, selecting data based on its numerical position in the data. 'iloc' follows this paradigm.

To select the first row of data in a DataFrame, we may use the following:

reviews.iloc[0]

실제 데이터셋을 가져와서 실습하는게 제일 나을 것 같다.

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving archive.zip to archive (1).zip

In [ ]:
import os
os.listdir()

['.config',
 'archive.zip',
 'fifa_world_cup_2026_player_performance.csv',
 'archive (1).zip',
 'sample_data']

In [ ]:
import zipfile
import os

zip_path = "fifa_world_cup_2026_player_performance.csv/archive.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall("data")
    print(z.namelist())

os.listdir("data")

['fifa_world_cup_2026_player_performance.csv']

['fifa_world_cup_2026_player_performance.csv']

In [ ]:
import os

csv_files = []

for root, dirs, files in os.walk("data"):
    for file in files:
        if file.endswith(".csv"):
            csv_files.append(os.path.join(root, file))

print(csv_files)

football = pd.read_csv(csv_files[0])
football.head()
#GPT의 도움으로 csv 파일 읽는데는 성공했다. 근데 이거 어떻게 혼자서 하지...

['data/fifa_world_cup_2026_player_performance.csv']

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

**CSV 데이터를 Colab에서 읽는 방법**

1. 업로드

from google.colab import files
uploaded=files.upload()

2. 현재 폴더 확인

import os
os.listdir()

이건 실제로 Colab에 어떤 파일이 올라왔는지 확인하는 코드.

3. 파일인지 폴더인지 확인

for name in os.listdir():
    print(name, "File?", os.path.isfile(name), "Folder?", os.path.isdir(name))

파일이라면 File? True / Folder? False가 출력되고, 폴더라면 그 반대.

4. CSV파일이면 바로 읽기

import pandas as pd
z=pd.read_csv("파일명.csv")
z.head()

5. Zip 파일이면 내부 확인하여 CSV만 골라 읽기

import zipfile
with zipfile.ZipFile("Zip파일명", "r") as z:
    csv_name=[name for name in z.namelist() if name.endswith(".csv")][0]
    file_name=pd.read_csv(z.open(csv_name))

file_name.head()

혹은 다음 코드를 이용하자.

In [ ]:
from google.colab import files
import os
import zipfile
import pandas as pd

uploaded = files.upload()

print("현재 폴더:")
print(os.listdir())

zip_files = [f for f in os.listdir() if f.endswith(".zip")]
csv_files = [f for f in os.listdir() if f.endswith(".csv") and os.path.isfile(f)]

if csv_files:
    print("CSV 파일 발견:", csv_files)
    football = pd.read_csv(csv_files[0])

elif zip_files:
    print("ZIP 파일 발견:", zip_files)
    zip_path = zip_files[0]

    with zipfile.ZipFile(zip_path, "r") as z:
        print("ZIP 내부 파일:")
        print(z.namelist())

        csv_inside = [name for name in z.namelist() if name.endswith(".csv")]
        football = pd.read_csv(z.open(csv_inside[0]))

else:
    raise FileNotFoundError("CSV 또는 ZIP 파일을 찾지 못했습니다.")

football.head()

이제 다시 Lesson 2로 돌아가서 실습 시작.

In [ ]:
football.iloc[0]
#column label과 첫 행을 함께 보여준다.

player_id                     P00055
player_name               Rodri Fati
                             ...
player_of_match_awards             0
tournament_rating                5.8
Name: 0, Length: 75, dtype: object

In [ ]:
football.shape
#.shape()가 아니라 .shape이다. 행 / 열 개수를 차례로 보여주는 튜플을 출력한다.

(54600, 75)

In [ ]:
football.iloc[10000]

player_id                       P00732
player_name               Keylor Calvo
                              ...
player_of_match_awards               0
tournament_rating                  0.0
Name: 10000, Length: 75, dtype: object

In [ ]:
football.iloc[:, 0]
#iloc을 이용하여 column을 뽑아낼 수도 있다. 조금 더 외우기 어렵게 생겼지만.

0        P00055
1        P00070
          ...
54598    P00991
54599    P00989
Name: player_id, Length: 54600, dtype: object

In [ ]:
football.iloc[:, 49]

0        4
1        0
        ..
54598    0
54599    0
Name: saves, Length: 54600, dtype: int64

In [ ]:
football.iloc[:3, 10]
#n열의 1, 2, 3열만 뽑아내고 싶을 땐 .iloc[:3, n+1]을 적용하면 된다.

0    RB Salzburg
1        Chelsea
2            AIK
Name: club_name, dtype: object

In [ ]:
football.iloc[10:20, 11]

10    16807939
11    41434814
        ...
18    22482687
19    37350285
Name: market_value_eur, Length: 10, dtype: int64

In [ ]:
#negative numbers can be used in selection ; this will start counting forwards from the end of the values
football.iloc[-5:]
#last five rows of the dataset

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

지금까지 iloc operator에 대해 실습하였다. iloc operator는 index-based selection이다. 이와 달리 loc operator는 label-based selection이다. 여기서는 해당하는 key에 맞는 value가 출력된다.

In [ ]:
football.loc[54596, 'player_name']

'Safaa Al-Khafaji'

In [ ]:
football.loc[:, ['player_name', 'nationality', 'creativity_score']]
#loc operator와 :를 이용하면 원하는 column을 뽑아낼 수 있다.

            player_name nationality  creativity_score
0            Rodri Fati     Spanish              55.9
1       Ansu Le Normand     Spanish              43.7
...                 ...         ...               ...
54598     Ibrahim Mhawi       Iraqi              39.6
54599  Mohannad Hussein       Iraqi              34.1

[54600 rows x 3 columns]

In [ ]:
football.set_index(["player_name", "nationality"])
#.set_index() 메서드를 이용하면 column을 row label으로 바꿀 수 있다. 예시처럼 여러 개를 만들 수도 있다.

,,player_id,age,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
player_name,nationality,,,,,,,,,,,,,,,,,,,,,
Rodri Fati,Spanish,P00055,26,Spain,3,Goalkeeper,195,75,Left,RB Salzburg,4384884,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
Ansu Le Normand,Spanish,P00070,19,Spain,18,Midfielder,178,75,Right,Chelsea,4918927,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ibrahim Mhawi,Iraqi,P00991,30,Iraq,3,Goalkeeper,190,81,Right,Kawasaki Frontale,47033556,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
Mohannad Hussein,Iraqi,P00989,27,Iraq,1,Goalkeeper,187,73,Right,Ulsan HD,39256189,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
football.head()
#중요한 것은, .set_index()를 실행해도 원본은 바뀌지 않는다는 것이다.
#원본을 바꾸려면 football=football.set_index()와 같이 지정해주어야 한다.

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [ ]:
#Conditional selection
football.nationality=='Spanish'
#bool type으로 모두 판별한다.

0         True
1         True
         ...
54598    False
54599    False
Name: nationality, Length: 54600, dtype: bool

In [ ]:
football.loc[football.team=='South Korea']
#이름 뭔데
#loc operator가 label-based selection이므로 iloc이 아니라 loc을 이용?

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
1456,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,1.9,59.8,25.1,70.6,66.1,0,0,188,0,5.4
1457,P00848,Jae-sung Yang,25,South Korean,South Korea,16,Midfielder,183,78,Right,...,2.1,42.2,38.0,39.8,35.8,0,3,355,1,6.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53740,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,0.0,66.3,19.9,69.6,70.1,0,0,266,0,0.0
53741,P00835,Min-jae Son,28,South Korean,South Korea,3,Goalkeeper,193,81,Left,...,0.0,78.9,32.6,60.7,78.0,0,0,194,0,0.0

In [ ]:
football.loc[(football.team=='South Korea') & (football.age>=25)]
#&을 이용하여 여러 기준으로 필터링 할 수 있다.

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
1456,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,1.9,59.8,25.1,70.6,66.1,0,0,188,0,5.4
1457,P00848,Jae-sung Yang,25,South Korean,South Korea,16,Midfielder,183,78,Right,...,2.1,42.2,38.0,39.8,35.8,0,3,355,1,6.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53740,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,0.0,66.3,19.9,69.6,70.1,0,0,266,0,0.0
53741,P00835,Min-jae Son,28,South Korean,South Korea,3,Goalkeeper,193,81,Left,...,0.0,78.9,32.6,60.7,78.0,0,0,194,0,0.0

In [ ]:
football.loc[(football.team=='South Korea') | (football.team=='Japan')]
#파이프 |는 or 연산자.

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
1456,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,1.9,59.8,25.1,70.6,66.1,0,0,188,0,5.4
1457,P00848,Jae-sung Yang,25,South Korean,South Korea,16,Midfielder,183,78,Right,...,2.1,42.2,38.0,39.8,35.8,0,3,355,1,6.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53740,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,0.0,66.3,19.9,69.6,70.1,0,0,266,0,0.0
53741,P00835,Min-jae Son,28,South Korean,South Korea,3,Goalkeeper,193,81,Left,...,0.0,78.9,32.6,60.7,78.0,0,0,194,0,0.0

In [ ]:
football.loc[football.team.isin(['South Korea', 'Japan', 'Germany'])]

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
1456,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,1.9,59.8,25.1,70.6,66.1,0,0,188,0,5.4
1457,P00848,Jae-sung Yang,25,South Korean,South Korea,16,Midfielder,183,78,Right,...,2.1,42.2,38.0,39.8,35.8,0,3,355,1,6.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53740,P00833,Son Hwang,30,South Korean,South Korea,1,Goalkeeper,189,78,Right,...,0.0,66.3,19.9,69.6,70.1,0,0,266,0,0.0
53741,P00835,Min-jae Son,28,South Korean,South Korea,3,Goalkeeper,193,81,Left,...,0.0,78.9,32.6,60.7,78.0,0,0,194,0,0.0

In [ ]:
#Exercise 1. Select the 'description' column from 'reviews' dataset and assign the result to the variable, desc.
desc=reviews["description"]

In [ ]:
#Exercise 4. Select the first 10 values from the 'description' column in 'reviews' dataset and assign the result to variable, first_descriptions
first_descriptions=reviews["description"][0:10]
#or
first_descriptions=reviews.loc[:9, "description"]