<a href="https://colab.research.google.com/github/dongmin-jeong/Pandas/blob/main/Kaggle_Pandas_26_06_30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kaggle, Pandas** 26-06-30

**Lesson 3. Summary Function and Maps**

In the last tutorial, we learned how to select relevant data out of a DataFrame ofr a Series, using .loc and .iloc. Plucking the right data out of our data representation is critical to getting work done, as we demonstrated in the exercises. In this section, we will cover different operation we can apply to our data to get the input "just right".

Again, we import the FIFA data.

In [ ]:
from google.colab import files
import os
import zipfile
import pandas as pd

uploaded = files.upload()

print("현재 폴더:")
print(os.listdir())

zip_files = [f for f in os.listdir() if f.endswith(".zip")]
csv_files = [f for f in os.listdir() if f.endswith(".csv") and os.path.isfile(f)]

if csv_files:
    print("CSV 파일 발견:", csv_files)
    football = pd.read_csv(csv_files[0])

elif zip_files:
    print("ZIP 파일 발견:", zip_files)
    zip_path = zip_files[0]

    with zipfile.ZipFile(zip_path, "r") as z:
        print("ZIP 내부 파일:")
        print(z.namelist())

        csv_inside = [name for name in z.namelist() if name.endswith(".csv")]
        football = pd.read_csv(z.open(csv_inside[0]))

else:
    raise FileNotFoundError("CSV 또는 ZIP 파일을 찾지 못했습니다.")

football.head()

Saving archive.zip to archive.zip
현재 폴더:
['.config', 'archive.zip', 'sample_data']
ZIP 파일 발견: ['archive.zip']
ZIP 내부 파일:
['fifa_world_cup_2026_player_performance.csv']

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

Pandas provides many simple "summary function" which restructure the data in some useful way.

In [ ]:
football.loc[:, "team"]

0        Spain
1        Spain
2        Spain
3        Spain
4        Spain
         ...
54595     Iraq
54596     Iraq
54597     Iraq
54598     Iraq
54599     Iraq
Name: team, Length: 54600, dtype: object

In [ ]:
football.height_cm.describe()

count    54600.000000
mean       181.654341
std          6.277792
min        163.000000
25%        177.000000
50%        182.000000
75%        186.000000
max        200.000000
Name: height_cm, dtype: float64

In [ ]:
football.creativity_score.describe()

count    54600.000000
mean        46.135778
std         22.424337
min          5.000000
25%         29.800000
50%         40.500000
75%         59.000000
max         99.000000
Name: creativity_score, dtype: float64

The method .describe() generates a high-level summary of the attributes of the given column. Also, it is type-aware.

In [ ]:
football.team.describe()

count     54600
unique       48
top       Qatar
freq       1716
Name: team, dtype: object

We have another methods, such as .mean(), .unique() - which prints a list of unique values, .value_counts() and so on.

In [ ]:
football.team.value_counts()

team
Qatar            1716
Jamaica          1534
Morocco          1430
Netherlands      1404
Italy            1378
Saudi Arabia     1352
Belgium          1326
Turkey           1300
Croatia          1274
Scotland         1274
Peru             1248
Canada           1248
Ecuador          1222
Panama           1222
Australia        1222
Tunisia          1222
Colombia         1196
Costa Rica       1196
Ghana            1170
Spain            1170
Uruguay          1170
Egypt            1170
Brazil           1170
Cameroon         1144
England          1144
Uzbekistan       1144
Portugal         1118
Denmark          1118
Serbia           1092
Algeria          1066
Iraq             1066
Nigeria          1040
Mexico           1040
Poland           1014
Ukraine           988
Senegal           988
United States     988
Iran              988
Chile             962
Sweden            936
Japan             936
South Africa      910
Switzerland       910
France            884
South Korea       884
Argentina         884
Germany           884
Austria           858
Name: count, dtype: int64

In [ ]:
football.team.unique()
#football의 team 칼럼에 서로 다른 값이 무엇이 있는지를 리스트로 만들어주는 메서드.
#출력되는 결과는 NumPy array이다.
#이걸 series로 만들어주려면
#pd.Series(football.team.unique())를 적용해주면 된다. 물론 import pandas as pd

array(['Spain', 'South Africa', 'Peru', 'Netherlands', 'Morocco',
       'Senegal', 'Algeria', 'Italy', 'Brazil', 'Scotland', 'Denmark',
       'Ghana', 'Iraq', 'Nigeria', 'Panama', 'Cameroon', 'Colombia',
       'Sweden', 'Poland', 'Jamaica', 'Croatia', 'Ukraine', 'Uzbekistan',
       'Ecuador', 'England', 'Australia', 'France', 'Saudi Arabia',
       'Chile', 'Canada', 'Egypt', 'South Korea', 'Belgium',
       'Switzerland', 'Iran', 'Japan', 'Germany', 'Argentina', 'Turkey',
       'Qatar', 'Costa Rica', 'Portugal', 'Uruguay', 'Mexico', 'Serbia',
       'United States', 'Tunisia', 'Austria'], dtype=object)

A map is a term, borrowed from mathematicss, for a function that takes one set of values and "maps" them to another set of values. In data science, we often have a need for creating new representations from existing data, or for transforming data from the format it is now in to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done.


There are two mapping methods that we use often.

In [ ]:
#map()
football_height_cm_mean=football.height_cm.mean()
football.height_cm.map(lambda p: p-football_height_cm_mean)

#football.height_cm.mean()을 이용해 선수들 키의 평균을 왼쪽 변수에 저장한다.
#출력된 결과는 height_cm 칼럼을 centering한 series. 해당 칼럼만 반환.

0        13.345659
1        -3.654341
2        -4.654341
3         0.345659
4         9.345659
           ...
54595    -4.654341
54596    -5.654341
54597    -8.654341
54598     8.345659
54599     5.345659
Name: height_cm, Length: 54600, dtype: float64

In [ ]:
football_height_cm_mean

np.float64(181.65434065934065)

In [ ]:
football.height_cm
#football에서 height_cm 열을 뽑아내어 Series로 만들어낸다.

0        195
1        178
2        177
3        182
4        191
        ...
54595    177
54596    176
54597    173
54598    190
54599    187
Name: height_cm, Length: 54600, dtype: int64

In [ ]:
#map()은 football.height_cm의 각 원소에 함수를 하나씩 적용한다.
#이때 lambda p:p-football_height_cm_mean은 series의 각 값 p를 받아서 평균을 빼는 함수.
#같은 원리로, 다음과 같이 표현할 수도 있다.

a=football.height_cm-football.height_cm.mean()
a

0        13.345659
1        -3.654341
2        -4.654341
3         0.345659
4         9.345659
           ...
54595    -4.654341
54596    -5.654341
54597    -8.654341
54598     8.345659
54599     5.345659
Name: height_cm, Length: 54600, dtype: float64

map(lambda ...)이 유용한 경우는 단순 산술연산이 아니라 각 원소를 어떤 규칙에 따라 바꿔야 할 때다. 예를 들어,

In [ ]:
football.height_cm.map(lambda h: "tall" if h>=185 else "short")

0         tall
1        short
2        short
3        short
4         tall
         ...
54595    short
54596    short
54597    short
54598     tall
54599     tall
Name: height_cm, Length: 54600, dtype: object

map() 함수와 함께 apply() 함수가 자주 사용된다.

apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

In [ ]:
a=football.creativity_score.mean()

def remean_creativity_score(row):
  row.creativity_score=row.creativity_score-a
  return row

football.apply(remean_creativity_score, axis='columns')
#이때 football DataFrame 원본은 그대로 저장되어 있다.
#football.head()를 출력하면 원본이 그대로 나온다.
#원본을 바꾸려면 column 전체 변수를 새로 지정해주어야 한다?

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,9.764222,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,-2.435778,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,52.864222,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,-3.835778,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,-12.635778,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,-18.435778,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,6.964222,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,8.864222,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,-6.535778,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,-12.035778,99.0,99.0,0,0,286,0,0.0

In [ ]:
#def remean_creativity_score(row):
 # row.creativity_score=row.creativity_score-a
  #return row

#위 코드의 함수 remean_creativity_score는 DataFrame의 한 행(row)를 입력으로 받는 함수.
#이를 통해 전체 row 하나하나에서 creativity_score 항을 creativity_score-a로 바꾼다.
#마지막 코드를 통해 이 바꾼 결과를 전체 DataFrame에 적용하는 것. 이때 사용하는게 바로 apply()

#football.apply(remean_creativity_score, axis='columns')

#이를 통해 football DataFrame의 각 행을 하나씩 순서대로 위에서 정의한 remean_creativity_score 함수에 적용
#반환되는 DataFrame은 creativity_score 열이 평균 중심화된 것으로 바뀐 DataFRame.

즉, apply()는 pandas 객체에 사용자가 정의한 함수를 적용할 때 사용된다. Series에 적용할 때는 map()과 같이 lambda x: 구문을 이용하여 각 원소에 함수를 적용한다. 반면 DataFrame에 쓰면 axis 설정에 따라 함수에 들어가는 단위가 달라지는데, axis=0 / axis='index'는 모두 함수를 각 열에 적용한다. 즉, 함수의 입력을 각 열으로 받아 함수를 적용한다. 반면 예시에서처럼 axis=1 / axis='columns'을 쓰면 함수를 각 행에 적용하고, 입력을 한 행 전체로 받는다.

여기서 lambda는 '익명함수'로 부르는 하나의 함수인데, lambda (입력값) : (반환값)의 구조로 작성한다.

Map 함수는 주로 series의 각 원소에 함수를 적용하여 주로 한 열의 값을 다를 값으로 변환하는데 반해, apply 함수는 sereis에도 그리고 DataFrame에도 모두 활용 가능하다. Series에 적용할 때는 map()과 거의 비슷하게 작동하고, DataFrame에 적용할 때는 행 또는 열 단위로 적용하여 여러 행 또는 여러 열을 동시에 참고할 때 유용하다.

In [ ]:
def classify_player(row):
  if row.height_cm>=185 and row.creativity_score>=60:
    return "good player"
  elif row.height_cm<=175 and row.creativity_score<=40:
    return "substitute player"
  else:
    return "other"

football["player_type"]=football.apply(classify_player, axis=1)
football

#원하는 칼럼 위치에 "player_type" 칼럼을 넣고 싶다면
#player_type=football.apply(classify_player, axis=1)
#football.insert(n(위치), "player_type"(인덱스 이름), player_type(value)) 처럼 하면 된다
#단, .insert() 메서드는 football DataFrame을 직접적으로 바꿈에 주의.

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating,player_type
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,44.2,55.9,42.0,51.8,0,0,242,0,5.8,other
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,38.2,43.7,31.1,52.7,0,3,342,0,5.5,other
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,99.0,99.0,83.4,54.8,1,1,245,0,8.4,other
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,19.8,42.3,40.9,78.5,5,3,422,0,6.7,other
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,44.1,33.5,60.0,56.6,0,0,440,0,5.7,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,41.9,27.7,31.3,40.5,1,0,97,0,0.0,other
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,64.2,53.1,64.8,64.3,2,0,206,0,0.0,other
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,75.4,55.0,65.0,64.5,1,1,359,0,0.0,other
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,96.3,39.6,99.0,99.0,0,0,342,0,0.0,other
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,99.0,34.1,99.0,99.0,0,0,286,0,0.0,other

**Exercise on Lesson 3**

5) Which wine is the "best bargain"? Create a variable, bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.

In [ ]:
#bargain_wine=reviews.loc[(reviews.points/reviews.price).idxmax(), 'title']
#'title'은 reviews 데이터프레임의 칼럼 인덱스 중 하나.
#.idxmax를 통해 points-to-price ratio가 가장 높은 행의 index label을 얻는다.
#.loc(.idxmax(), 'title')은 idxmax() 행의 title에 저장되어 있는 값을 가져온다.
#데이터프레임의 특정 행과 열을 명확히 지정할 때는 dataframe.loc[row_index, column_name]을 이용한다.

6) There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset. (For simplicity, let's ignore the capitalized versions of these words.)

In [ ]:
#n_tropical=reviews.description.str.contains("tropical").sum()
#n_fruity=reviews.description.str.contains("fruity").sum()

#descriptor_counts=pd.Series(
 #   [n_tropical, n_fruity],
  #  index=["tropical", "fruity"])


#str.contains() 메서드는 각 행마다 해당하는 문자열이 들어갔는지 판단하여
#True / False 값이 포함된 boolean series를 만든다.
#즉, n_tropical=reviews.description.str.contains("tropical") 자체는 Boolean series가 된다.
#.sum()을 이용하면 Boolean을 세어 True면 1, False면 0을 추가하는데
#따라서 n_tropical=~.sum()은 tropical 단어가 포함된 행의 개수가 된다.
#마지막으로 Series를 만들어주면 된다.

7) We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star. Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points. Create a series star_ratings with the number of stars corresponding to each review in the dataset.

In [ ]:
#def star_ratings_ft(row):
 #   if row.points>=95:
  #      return 3
   # elif row.country=="Canada":
    #    return 3
    #elif 85<=row.points<95:
     #   return 2
    #else:
     #   return 1

#star_ratings=reviews.apply(star_ratings_ft, axis=1)

**Lesson 7. Grouping and Sorting**

Maps allow us to transform data in a DataFrame or Series one value at a time for an entire column. However, often we want to group our data, and then do something specific to the group the data is in.

In this section, we study the groupby() operation.

One function we've been using heavily thuus far is the value_counts() function. We can replicate what value_counts() does by doing the following:

In [ ]:
football.groupby('creativity_score').creativity_score.count()
#groupby() 안에 넣는 이름이 가져올 칼럼의 index label이 되어야 한다.
#'creativity_score'를 기준으로 groupize하고 각 group에서 creativity_score를 count.

creativity_score
5.0      147
5.1        5
5.2        3
5.3        3
5.4        6
        ...
98.6      12
98.7      13
98.8      15
98.9      14
99.0    2108
Name: creativity_score, Length: 941, dtype: int64

We can use any of the summary functions we've used before with this data.

In [ ]:
football.groupby('creativity_score').height_cm.min()
#'creativity_score'로 groupize한 카테고리에서 height_cm이 가장 작은 항을 추출한다.

creativity_score
5.0     172
5.1     173
5.2     179
5.3     183
5.4     184
       ...
98.6    173
98.7    173
98.8    172
98.9    170
99.0    163
Name: height_cm, Length: 941, dtype: int64

In [ ]:
football.groupby('creativity_score').height_cm.max()
#'creativity_score'로 groupize한 카테고리에서 height_cm이 가장 큰 항을 추출한다.

creativity_score
5.0     200
5.1     192
5.2     192
5.3     190
5.4     193
       ...
98.6    190
98.7    186
98.8    190
98.9    189
99.0    194
Name: height_cm, Length: 941, dtype: int64

We can think of each group we generate as being a slice of our DataFrame containing only data with values that match. This DataFrame is accessible to us directly using the apply() method.

In [ ]:
football.groupby('team').apply(lambda df: df.player_id.iloc[0])
#football 데이터프레임에서 'team'으로 groupize한 다음, 각 group에서 첫 번째 선수 번호를 뽑아내어 만든 series.

/tmp/ipykernel_4569/350943660.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  football.groupby('team').apply(lambda df: df.player_id.iloc[0])

team
Algeria          P01172
Argentina        P00495
Australia        P00911
Austria          P00315
Belgium          P00157
Brazil           P00470
Cameroon         P01119
Canada           P00705
Chile            P00548
Colombia         P00521
Costa Rica       P00729
Croatia          P00211
Denmark          P00263
Ecuador          P00600
Egypt            P01199
England          P00079
France           P00002
Germany          P00027
Ghana            P01093
Iran             P00859
Iraq             P00990
Italy            P00105
Jamaica          P00755
Japan            P00807
Mexico           P00677
Morocco          P01041
Netherlands      P00133
Nigeria          P01068
Panama           P00781
Peru             P00626
Poland           P00340
Portugal         P00185
Qatar            P00937
Saudi Arabia     P00886
Scotland         P00444
Senegal          P01017
Serbia           P00288
South Africa     P01225
South Korea      P00833
Spain            P00055
Sweden           P00366
Switzerland      P00235
Tunisia          P01147
Turkey           P00392
Ukraine          P00417
United States    P00651
Uruguay          P00575
Uzbekistan       P00963
dtype: object

We can also group by more than one column. For example, we pick the best creative player by team and age.

In [ ]:
football.groupby(["team", "age"]).apply(lambda df: df.loc[df.creativity_score.idxmax()])
#해당선수의 이름만 알고 싶다면 .loc[df.creativity_score(), "player_name"]을 대입.
#먼저 groupby(["team", "age"])에 의해 데이터프레임 전체를 groupize하고
#.apply(lambda 입력 : 출력)을 통해 groupize한 데이터프레임을 하나하나 입력값으로 가져와
#df.creativity_score.idxmax()인 index를 가진 행을 출력하는 코드.

/tmp/ipykernel_4569/3496055312.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  football.groupby(["team", "age"]).apply(lambda df: df.loc[df.creativity_score.idxmax()])

               player_id           player_name  age nationality        team  \
team       age
Algeria    18     P01185          Sofiane Bayo   18    Algerian     Algeria
           19     P01182           Islam Touzi   19    Algerian     Algeria
           20     P01180           Adam Toudic   20    Algerian     Algeria
           21     P01189             Adam Kara   21    Algerian     Algeria
           22     P01174      Riyad Bensebaini   22    Algerian     Algeria
...                  ...                   ...  ...         ...         ...
Uzbekistan 31     P00986   Jaloliddin Rashidov   31       Uzbek  Uzbekistan
           32     P00965     Otabek Nasrullaev   32       Uzbek  Uzbekistan
           33     P00988  Husniddin Nasrullaev   33       Uzbek  Uzbekistan
           34     P00973      Bobir Eshmurodov   34       Uzbek  Uzbekistan
           35     P00985       Otabek Sattorov   35       Uzbek  Uzbekistan

                jersey_number    position  height_cm  weight_kg  \
team       age
Algeria    18              15  Midfielder        178         68
           19              12    Defender        178         69
           20              10    Defender        184         78
           21              19  Midfielder        177         75
           22               4    Defender        193         80
...                       ...         ...        ...        ...
Uzbekistan 31              24     Forward        183         81
           32               3  Goalkeeper        195         83
           33              26     Forward        182         74
           34              11    Defender        185         82
           35              23     Forward        182         73

               preferred_foot  ... pressure_resistance  creativity_score  \
team       age                 ...
Algeria    18           Right  ...                80.4              89.3
           19           Right  ...                41.4              53.7
           20           Right  ...                59.0              54.7
           21           Right  ...                57.1              92.6
           22           Right  ...                66.3              47.3
...                       ...  ...                 ...               ...
Uzbekistan 31           Right  ...                93.9              99.0
           32           Right  ...                66.7              55.3
           33           Right  ...                45.0              62.0
           34           Right  ...                60.0              54.2
           35            Left  ...                44.4              52.4

               consistency_score clutch_performance_score  \
team       age
Algeria    18               83.0                     51.9
           19               48.5                     48.4
           20               59.2                     53.0
           21               76.8                     46.4
           22               76.5                     38.5
...                          ...                      ...
Uzbekistan 31               95.2                     44.7
           32               60.1                     52.7
           33               52.7                     53.4
           34               86.5                     42.3
           35               36.0                     55.5

               total_goals_tournament total_assists_tournament  \
team       age
Algeria    18                       0                        1
           19                       0                        0
           20                       0                        0
           21                       0                        4
           22                       0                        0
...                               ...                      ...
Uzbekistan 31                       1                        1
           32                       0                        0
           33                       2                        2
           34                       0                        0
           35                       4                        2

               total_minutes_tournament player_of_match_awards  \
team       age
Algeria    18                       119                      0
           19                       107                      0
           20                       216                      0
           21                       426                      0
           22                       274                      0
...                                 ...                    ...
Uzbekistan 31                       325                      0
           32                       278                      0
           33                       410                      0
           34                       279                      0
           35                       403                      0

               tournament_rating  player_type
team       age
Algeria    18                0.0        other
           19                0.0        other
           20                5.4        other
           21                6.4        other
           22                0.0        other
...                          ...          ...
Uzbekistan 31                6.8        other
           32                0.0        other
           33                0.0        other
           34                6.6        other
           35                5.2        other

[624 rows x 76 columns]

Another groupby() method worth mentioning is agg(), which let us run a bunch of different functions on our DataFrame simultaneously.

agg()를 이용하면 여러 함수를 한 번에 데이터프레임에 적용하여 새로운 데이터프레임을 얻을 수 있다.

In [ ]:
football.groupby(['nationality']).height_cm.agg([len, min, max])
#len()함수는 그 group에 몇 개의 term이 있는지를 알려준다. 예를들어 Algerian group에는 총 1066명의 선수가 포함되어 있다.

/tmp/ipykernel_4569/1512851168.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  football.groupby(['nationality']).height_cm.agg([len, min, max])
/tmp/ipykernel_4569/1512851168.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  football.groupby(['nationality']).height_cm.agg([len, min, max])

                len  min  max
nationality
Algerian       1066  168  193
American        988  169  197
Argentine       884  172  189
Australian     1222  164  196
Austrian        858  171  192
Belgian        1326  164  200
Brazilian      1170  169  193
Cameroonian    1144  167  190
Canadian       1248  171  198
Chilean         962  168  190
Colombian      1196  171  193
Costa Rican    1196  171  192
Croatian       1274  168  192
Danish         1118  171  191
Dutch          1404  166  192
Ecuadorian     1222  169  197
Egyptian       1170  171  195
English        1144  171  197
French          884  173  191
German          884  169  195
Ghanaian       1170  163  192
Iranian         988  167  192
Iraqi          1066  171  191
Italian        1378  163  192
Jamaican       1534  170  190
Japanese        936  169  194
Mexican        1040  172  192
Moroccan       1430  168  191
Nigerian       1040  168  194
Panamanian     1222  170  193
Peruvian       1248  167  195
Polish         1014  170  191
Portuguese     1118  169  190
Qatari         1716  171  200
Saudi          1352  168  196
Scottish       1274  169  197
Senegalese      988  163  191
Serbian        1092  170  193
South African   910  169  190
South Korean    884  173  196
Spanish        1170  171  195
Swedish         936  165  192
Swiss           910  171  194
Tunisian       1222  168  190
Turkish        1300  166  191
Ukrainian       988  169  191
Uruguayan      1170  174  190
Uzbek          1144  169  195

**Multi-indexes**

A multi-index differs from a regular index in that it has multiple levels. For example,

In [ ]:
countries_age=football.groupby(['nationality', 'age']).height_cm.agg([len, min, max])
countries_age
#여러개의 index를 이용하여 multi-index groupize하고, agg()를 이용하여 height_cm 칼럼에서 len / min / max 함수를 적용하였다.
#football.groupby(["team", "age"]).apply(lambda df: df.loc[df.creativity_score.idxmax()])
#이전에 봤던 이 코드는 'team' , 'age'라는 multi-index를 이용하여 groupize한 뒤
#각 그룹에서 creativity_score가 가장 큰 행 전체를 뽑아내는 코드.
#이번에 작성한 코드는 multi-index를 이용하여 데이터 전체를 원하는 함수 in agg()으로 정리하는 코드

/tmp/ipykernel_4569/4131798643.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  countries_age=football.groupby(['nationality', 'age']).height_cm.agg([len, min, max])
/tmp/ipykernel_4569/4131798643.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  countries_age=football.groupby(['nationality', 'age']).height_cm.agg([len, min, max])

                 len  min  max
nationality age
Algerian    18    41  178  178
            19    41  178  178
            20    82  183  184
            21    82  177  187
            22    41  193  193
...              ...  ...  ...
Uzbek       31    44  183  183
            32    88  185  195
            33    88  182  191
            34    44  185  185
            35    44  182  182

[624 rows x 3 columns]

In [ ]:
type(countries_age)
#countries_age 자체의 타입

pandas.core.frame.DataFrame

In [ ]:
m1=countries_age.index
type(m1)
#countries_age의 index를 따로 꺼낸 뒤 그 index의 타입을 본 것

pandas.core.indexes.multi.MultiIndex

In [ ]:
m1

MultiIndex([('Algerian', 18),
            ('Algerian', 19),
            ('Algerian', 20),
            ('Algerian', 21),
            ('Algerian', 22),
            ('Algerian', 23),
            ('Algerian', 24),
            ('Algerian', 25),
            ('Algerian', 27),
            ('Algerian', 28),
            ...
            (   'Uzbek', 25),
            (   'Uzbek', 26),
            (   'Uzbek', 27),
            (   'Uzbek', 28),
            (   'Uzbek', 30),
            (   'Uzbek', 31),
            (   'Uzbek', 32),
            (   'Uzbek', 33),
            (   'Uzbek', 34),
            (   'Uzbek', 35)],
           names=['nationality', 'age'], length=624)

Group을 여러 칼럼을 기준으로 하여 얻은 multi-index는 강력하지만 처음에는 다루기 까다롭다. 그래서 실무에서는 groupby 결과를 다시 일반 DataFrame으로 만들기 위해 reset_index() 메서드를 이용하곤 한다.

인덱스가 여러 층으로 구성되어 있는데 이건 실제 칼럼이 아니고, 헷갈리기 쉽다. 그래서 rest_index() 메서드를 이용하여 multi-index의 index level을 일반 칼럼으로 빼낸다.

In [ ]:
countries_age.reset_index()
#Multi-index를 모두 제거하여 column으로 바꿔놓았다.
#이러면 .loc / .iloc 등 조작이 좀 더 쉬워질 때가 있다 - 적어도 초보자에게는

    nationality  age  len  min  max
0      Algerian   18   41  178  178
1      Algerian   19   41  178  178
2      Algerian   20   82  183  184
3      Algerian   21   82  177  187
4      Algerian   22   41  193  193
..          ...  ...  ...  ...  ...
619       Uzbek   31   44  183  183
620       Uzbek   32   88  185  195
621       Uzbek   33   88  182  191
622       Uzbek   34   44  185  185
623       Uzbek   35   44  182  182

[624 rows x 5 columns]

**Sorting**

Looking again at countries_age, we can see that grouping returns data in index order, not in value order. That is, when outputting the result of a groupby, the order of the rows is dependent on the values in the index, not int the data. We can use sort_values() method to get data in the order we want.

In [ ]:
countries_age=countries_age.reset_index()
countries_age.sort_values(by='len')
#len이라는 데이터값을 기준으로 countreis_age를 sorting하였다.

    nationality  age  len  min  max
63     Austrian   29   33  173  173
62     Austrian   28   33  184  184
67     Austrian   34   33  182  182
64     Austrian   30   33  171  171
68     Austrian   35   33  178  178
..          ...  ...  ...  ...  ...
266    Ghanaian   28  270  172  192
191       Dutch   25  270  166  191
327    Japanese   28  288  177  192
115    Canadian   28  336  172  189
315    Jamaican   27  354  178  189

[624 rows x 5 columns]

In [ ]:
#sort_values의 기본값은 오름차순 / 내림차순으로 sorting하고 싶으면
countries_age.sort_values(by='len', ascending=False)
#ascending=False 코드를 추가하여 len을 내림차순으로 정리하였다.

    nationality  age  len  min  max
315    Jamaican   27  354  178  189
115    Canadian   28  336  172  189
327    Japanese   28  288  177  192
191       Dutch   25  270  166  191
266    Ghanaian   28  270  172  192
..          ...  ...  ...  ...  ...
68     Austrian   35   33  178  178
67     Austrian   34   33  182  182
64     Austrian   30   33  171  171
62     Austrian   28   33  184  184
63     Austrian   29   33  173  173

[624 rows x 5 columns]

In [ ]:
#다시 index 순서대로(원래대로) 배열하고 싶으면
countries_age.sort_index()

    nationality  age  len  min  max
0      Algerian   18   41  178  178
1      Algerian   19   41  178  178
2      Algerian   20   82  183  184
3      Algerian   21   82  177  187
4      Algerian   22   41  193  193
..          ...  ...  ...  ...  ...
619       Uzbek   31   44  183  183
620       Uzbek   32   88  185  195
621       Uzbek   33   88  182  191
622       Uzbek   34   44  185  185
623       Uzbek   35   44  182  182

[624 rows x 5 columns]

In [ ]:
#한 번에 여러 칼럼을 기준으로 sorting할 수도 있다.
countries_age.sort_values(by=['len', 'age'])
#이러면 len 오름차순 / 나이 오름차순으로 sorting된다.
#어떤 것이 앞에 오느냐에 따라 그것을 기준으로 먼저 sorting하고 두 번째 기준을 다음 sorting 기준으로 반영한다.

    nationality  age  len  min  max
62     Austrian   28   33  184  184
63     Austrian   29   33  173  173
64     Austrian   30   33  171  171
67     Austrian   34   33  182  182
68     Austrian   35   33  178  178
..          ...  ...  ...  ...  ...
191       Dutch   25  270  166  191
266    Ghanaian   28  270  172  192
327    Japanese   28  288  177  192
115    Canadian   28  336  172  189
315    Jamaican   27  354  178  189

[624 rows x 5 columns]

**Exercise**

4. What are the most expensive wine varieties? Create a variable sorted_varieties containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties)

In [ ]:
#sorted_varieties = price_extremes.sort_values(by=['min', 'max'], ascending=False)
#price_extremes는 직전에 만든 데이터프레임
#descendign order로 정렬하기 위하여 ascending=False를 넣음
#min / max의 descending / ascending을 따로 정의하고 싶다면
#.sort_values(by=['min', 'max'], ascendign=[False, True])처럼 작성하면 됨.

**Titanic CSV 데이터 실습**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [ ]:
titanic=pd.read_csv('titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Titanic CSV Pandas 실습 질문 모음

## 1단계: 데이터 구조 파악

1. Titanic 데이터에는 몇 개의 행과 몇 개의 열이 있는가?

2. 각 열의 이름과 데이터 타입은 무엇인가?

3. 결측치가 있는 열은 무엇이고, 각 열마다 결측치가 몇 개인가?

4. 승객 나이(`Age`)의 평균, 중앙값, 최솟값, 최댓값은 각각 얼마인가?

5. 생존자 수와 사망자 수는 각각 몇 명인가?

---

## 2단계: `loc`, `iloc`, indexing 연습

6. 첫 10명의 승객 정보를 `iloc`으로 출력해라.

7. `Name`, `Sex`, `Age`, `Survived` 열만 골라서 출력해라.

8. 나이가 18세 미만인 승객들만 골라서 출력해라.

9. 여성 승객 중 생존한 사람들만 골라서 출력해라.

10. 1등석(`Pclass == 1`) 승객 중 나이가 40세 이상인 사람들의 이름과 나이를 출력해라.

11. `PassengerId`를 index로 설정한 뒤, 특정 `PassengerId`의 정보를 `loc`으로 가져와라.

---

## 3단계: `groupby`와 summary function

12. 전체 생존율은 얼마인가?

13. 성별(`Sex`)에 따른 생존율은 각각 얼마인가?

14. 객실 등급(`Pclass`)별 생존율은 각각 얼마인가?

15. 성별과 객실 등급을 함께 기준으로 묶었을 때 생존율은 어떻게 달라지는가?

16. 객실 등급별 평균 나이와 평균 운임(`Fare`)은 얼마인가?

17. 탑승 항구(`Embarked`)별 승객 수와 생존율은 어떻게 다른가?

---

## 4단계: sorting 연습

18. 운임(`Fare`)이 가장 비싼 승객 10명은 누구인가?

19. 나이가 가장 많은 승객 10명은 누구인가?

20. 생존자 중 운임을 가장 적게 낸 승객들은 누구인가?

21. 객실 등급별 평균 운임을 계산한 뒤, 평균 운임이 높은 순서대로 정렬해라.

22. 성별과 객실 등급별 생존율을 계산한 뒤, 생존율이 높은 순서대로 정렬해라.

---

## 5단계: mapping / apply 연습

23. `Sex` 열의 값을 `male -> 0`, `female -> 1`로 바꾼 새로운 열 `SexCode`를 만들어라.

24. `Age`를 기준으로 `Child`, `Adult`, `Senior` 같은 나이 그룹을 만드는 새로운 열 `AgeGroup`을 만들어라.

    예시:

    ```text
    0 <= Age < 18: Child
    18 <= Age < 60: Adult
    60 <= Age: Senior
    ```

25. `Fare`를 기준으로 저가, 중가, 고가 티켓 그룹을 나누는 열을 만들어라.

26. 이름(`Name`)에서 `Mr.`, `Mrs.`, `Miss.`, `Master.` 같은 호칭을 추출해서 `Title` 열을 만들어라.

27. 호칭별 생존율을 계산해라.

---

## 6단계: 조금 더 분석다운 질문

28. “여성과 아이가 먼저 구조되었다”는 말이 Titanic 데이터에서 실제로 어느 정도 맞는가?

29. 객실 등급이 생존율에 영향을 준 것으로 보이는가?

30. 운임을 많이 낸 승객일수록 생존율이 높았는가?

31. 가족과 함께 탄 승객이 혼자 탄 승객보다 생존율이 높았는가?

    힌트: `SibSp + Parch`를 이용해서 가족 수를 만들 수 있다.

32. 혼자 탑승한 승객과 가족 동반 승객의 생존율을 비교해라.

33. 나이대별 생존율은 어떻게 다른가?

34. 성별, 객실 등급, 나이대를 동시에 고려하면 어떤 패턴이 보이는가?

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic.shape
#891행, 12열 데이터프레임

(891, 12)

In [ ]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
#결측치를 확인하는 메서드는 .isnull(). Boolean dataframe을 내놓는다.
titanic.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
titanic.isnull().sum()
#.sum() 메서드를 이용하면 각 열별로 결측치가 True인 항의 개수를 합한 Series를 내놓는다.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
a=titanic.Age.mean()
b=titanic.Age.median()
c=titanic.Age.min()
d=titanic.Age.max()

print("Mean is "+str(a), "Median is "+str(b), "Min is "+str(c), "Max is "+str(d), sep='\n')

Mean is 29.69911764705882
Median is 28.0
Min is 0.42
Max is 80.0

In [ ]:
sur=titanic.Survived.sum()
dea=len(titanic)-int(sur)

print("Survivors are "+str(sur), "Deads are "+str(dea), sep='\n')

Survivors are 342
Deads are 549

**26-07-01** 이어서

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic.iloc[0:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
titanic.loc[:, ["Name", "Sex", "Age", "Survived"]]

                                                  Name     Sex   Age  Survived
0                              Braund, Mr. Owen Harris    male  22.0         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                               Heikkinen, Miss. Laina  female  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                             Allen, Mr. William Henry    male  35.0         0
..                                                 ...     ...   ...       ...
886                              Montvila, Rev. Juozas    male  27.0         0
887                       Graham, Miss. Margaret Edith  female  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN         0
889                              Behr, Mr. Karl Howell    male  26.0         1
890                                Dooley, Mr. Patrick    male  32.0         0

[891 rows x 4 columns]

In [ ]:
names=titanic.loc[titanic["Age"]>= 18, "Name"]
print(names)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
885                 Rice, Mrs. William (Margaret Norton)
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 601, dtype: object

In [ ]:
names_u=titanic.loc[titanic["Age"]<18, "Name"]
print(names_u)

7               Palsson, Master. Gosta Leonard
9          Nasser, Mrs. Nicholas (Adele Achem)
10             Sandstrom, Miss. Marguerite Rut
14        Vestrom, Miss. Hulda Amanda Adolfina
16                        Rice, Master. Eugene
                        ...
850    Andersson, Master. Sigvard Harald Elias
852                    Boulos, Miss. Nourelain
853                  Lines, Miss. Mary Conover
869            Johnson, Master. Harold Theodor
875           Najib, Miss. Adele Kiamie "Jane"
Name: Name, Length: 113, dtype: object

In [ ]:
survived_women=titanic.loc[(titanic.Sex=="female") & (titanic.Survived==1), "Name"]
print(survived_women)

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
                             ...
874                Abelson, Mrs. Samuel (Hannah Wizosky)
875                     Najib, Miss. Adele Kiamie "Jane"
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: Name, Length: 233, dtype: object

In [ ]:
a=titanic.loc[(titanic.Pclass==1) & (titanic.Age>=40), ["Name", "Age"]]
print(a)

                                                  Name   Age
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
30                            Uruchurtu, Don. Manuel E  40.0
35                      Holverson, Mr. Alexander Oskar  42.0
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0
..                                                 ...   ...
856         Wick, Mrs. George Dennick (Mary Hitchcock)  45.0
857                             Daly, Mr. Peter Denis   51.0
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0

[81 rows x 2 columns]

In [ ]:
titanic.set_index("PassengerId")

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
titanic.set_index("PassengerId").loc[0:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
total_survivor=titanic.Survived.sum()/len(titanic)
print(float("{:.3f}".format(total_survivor))*100, "%", sep="")

38.4%

In [ ]:
survived=titanic.groupby("Sex").Survived.sum()
a=survived["female"]/len(titanic)
b=survived['male']/len(titanic)
print(float("{:.2f}".format(a))*100, "%", sep="")
print(float("{:.3f}".format(b))*100, "%", sep="")
#survived는 pandas series이다.
#series에서 index를 바로 꺼내올 때는 ["index_name"]을 이용...

26.0%
12.2%

In [ ]:
Pclass_by=titanic.groupby("Pclass").Survived.sum()
a=Pclass_by[1]/len(titanic)
b=Pclass_by[2]/len(titanic)
c=Pclass_by[3]/len(titanic)
print(float("{:.2f}".format(a))*100, "%", sep="")
print(float("{:.3f}".format(b))*100, "%", sep="")
print(float("{:.3f}".format(c))*100, "%", sep="")

15.0%
9.8%
13.4%

In [ ]:
sex_and_class=titanic.groupby(["Sex", "Pclass"]).Survived.sum()/len(titanic)*100
sex_and_class

Sex     Pclass
female  1         10.213244
        2          7.856341
        3          8.080808
male    1          5.050505
        2          1.907969
        3          5.274972
Name: Survived, dtype: float64

In [ ]:
age_and_fare=titanic.groupby("Pclass")[["Age", "Fare"]].mean()
age_and_fare

              Age       Fare
Pclass
1       38.233441  84.154687
2       29.877630  20.662183
3       25.140620  13.675550

In [ ]:
age_and_fare=titanic.groupby("Pclass").loc[:, ["Age", "Fare"]]
age_and_fare
#DataFrameGroupby는 loc이란 attribute가 없다... 바로 위에처럼
#[]을 이용하여 index를 즉시 읽어야 한다.

AttributeError: 'DataFrameGroupBy' object has no attribute 'loc'

In [ ]:
titanic.groupby("Pclass")[["Age", "Fare"]].mean()

              Age       Fare
Pclass
1       38.233441  84.154687
2       29.877630  20.662183
3       25.140620  13.675550

In [ ]:
a=titanic.groupby("Embarked").PassengerId.agg(len).to_list()
b=titanic.groupby("Embarked").Survived.sum().to_list()
print(a)
print(b)

[168, 77, 644]
[93, 30, 217]

In [ ]:
titanic.sort_values("Fare", ascending=False)[["Name", "Fare"]].head(10)

                                                Name      Fare
679               Cardeza, Mr. Thomas Drake Martinez  512.3292
258                                 Ward, Miss. Anna  512.3292
737                           Lesurer, Mr. Gustave J  512.3292
88                        Fortune, Miss. Mabel Helen  263.0000
438                                Fortune, Mr. Mark  263.0000
341                   Fortune, Miss. Alice Elizabeth  263.0000
27                    Fortune, Mr. Charles Alexander  263.0000
742            Ryerson, Miss. Susan Parker "Suzette"  262.3750
311                       Ryerson, Miss. Emily Borie  262.3750
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208

In [ ]:
titanic.sort_values("Age", ascending=False)[["Name", "Age", "Survived"]].head(10)

                                     Name   Age  Survived
630  Barkworth, Mr. Algernon Henry Wilson  80.0         1
851                   Svensson, Mr. Johan  74.0         0
493               Artagaveytia, Mr. Ramon  71.0         0
96              Goldschmidt, Mr. George B  71.0         0
116                  Connors, Mr. Patrick  70.5         0
745          Crosby, Capt. Edward Gifford  70.0         0
672           Mitchell, Mr. Henry Michael  70.0         0
33                  Wheadon, Mr. Edward H  66.0         0
456             Millet, Mr. Francis Davis  65.0         0
54         Ostby, Mr. Engelhart Cornelius  65.0         0

In [ ]:
survivors=titanic[titanic.Survived==1]
min_fare=survivors.Fare.min()
survivors[survivors.Fare==min_fare][["Name", "Fare", "Embarked"]]

                             Name  Fare Embarked
271  Tornquist, Mr. William Henry   0.0        S

In [139]:
mean_fare=titanic.groupby("Pclass").Fare.mean()
mean_fare.sort_values(ascending=False)

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [152]:
s=titanic.groupby(['Sex', 'Pclass'])['Survived'].agg(['count', 'sum'])
s["survivor_rate"]=s["sum"]/s["count"]*100
s.sort_values(by="survivor_rate", ascending=False)

               count  sum  survivor_rate
Sex    Pclass
female 1          94   91      96.808511
       2          76   70      92.105263
       3         144   72      50.000000
male   1         122   45      36.885246
       2         108   17      15.740741
       3         347   47      13.544669